=== lewiswill/Memo-XML-Project/memo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name = "memostore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nextID" type="xs:integer">
                    <xs:element name = "memos">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="memo" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:all>
                                                <xs:element name="title" type="xs:string"/>
                                                <xs:element name="sender" type="xs:string"/>
                                                <xs:element name="recipients" type="xs:string"/>
                                                <xs:element name="date" type="xs:date"/>
                                                <xs:element name="message" type="xs:string"/>
                                                <xs:element name="url" type="xs:string"/>
                                            </xs:all>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
 </xs:schema>

=== lewiswill/Memo-XML-Project/memo.xml
<?xml version="1.0"?>
<memostore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="memo.xsd">
  <nextID>13</nextID>
  <memos>
    <memo id="12">
      <title>Hello</title>
      <sender>John</sender>
      <recipients>Will</recipients>
      <date>2017-10-10</date>
      <message>Hi did this work?</message>
      <url>www.didthiswork.com</url>
    </memo>
    <memo id="11">
      <title>Another test</title>
      <sender>Will</sender>
      <recipients>Hannah</recipients>
      <date>2016-10-22</date>
      <message>I love to test this!</message>
      <url>www.testingtestingtesting.com</url>
    </memo>
    <memo id="10">
      <title>Does this work?</title>
      <sender>Will</sender>
      <recipients>The tester guy</recipients>
      <date>2017-10-24</date>
      <message>Is this working yet?</message>
      <url>www.tellmenow.com</url>
    </memo>
    <memo id="9">
      <title>Yet another test</title>
      <sender>John</sender>
      <recipients>Jean</recipients>
      <date>2017-10-21</date>
      <message>Hey, is this working?</message>
      <url>www.maybe.com</url>
    </memo>
    <memo id="8">
      <title>Another Test Memo</title>
      <sender>Brian</sender>
      <recipients>Steve</recipients>
      <date>2017-10-20</date>
      <message>Hey Steve, hurry up and fix the javascript!</message>
      <url>www.now.com</url>
    </memo>
    <memo id="7">
      <title>Man Utd Manager Application</title>
      <sender>Steve Bruce</sender>
      <recipients>Alex Ferguson</recipients>
      <date>2017-01-01</date>
      <message>Hey, can I have the job Fergie? please!!</message>
      <url>www.stevebruce.com</url>
    </memo>
    <memo id="6">
      <title>Final Test for tonight</title>
      <sender>william</sender>
      <recipients>hannah</recipients>
      <date>2017-10-14</date>
      <message>This is the last test This is the last test This is the last test This is the last test This is the last test This is the last test This is the last test This is the last test This is the last test This is the last test</message>
      <url>www.bye.com</url>
    </memo>
    <memo id="5">
      <title>More testing</title>
      <sender>John</sender>
      <recipients>Mary</recipients>
      <date>2017-10-14</date>
      <message>Yeah test more</message>
      <url>www.howaboutno.com</url>
    </memo>
    <memo id="4">
      <title>Ok Lads....</title>
      <sender>Mr Wong</sender>
      <recipients>William Lewis</recipients>
      <date>2017-10-14</date>
      <message>Hurry up and get this memo machine working. PRONTO!</message>
      <url>www.hurryup.com</url>
    </memo>
    <memo id="3">
      <title>I dont particulary enjoy sending out memos..</title>
      <sender>Martin</sender>
      <recipients>Chris</recipients>
      <date>2016-09-10</date>
      <message>But would you PLEASE stop leaving the fridge door open! Thanks.</message>
      <url>www.donotignorethis.com</url>
    </memo>
    <memo id="2">
      <title>Second Memo</title>
      <sender>William Lewis</sender>
      <recipients>Hannah Morrison</recipients>
      <date>2017-10-14</date>
      <message>Ok, let me know when your ready</message>
      <url>www.bbc.com</url>
    </memo>
    <memo id="1">
      <title>Hi Hannah!</title>
      <sender>Mr William Lewis</sender>
      <recipients>Mrs Hannah Morrison</recipients>
      <date>2017-10-12 </date>
      <message>Here is a YAYA. Here is a message. Here is a message. 
      Here is a message. Here is a message. Here is a message. 
      Here is a message. Here is a message. Here is a message. 
      Here is a message. Here is a message. Here is a message. 
      Here is a message. Here is a message. Here is a message.</message>
      <url>www.furthermemoreading.org</url>
    </memo>
  </memos>
</memostore>
